# Generated by Django 3.0.6 on 2020-06-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_telegram_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastmessage',
            options={'ordering': ['-sent_at']},
        ),
    ]
