# Generated by Django 3.0.6 on 2020-06-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20200609_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
