# Generated by Django 3.0.7 on 2020-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_lastmessage_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastmessage',
            name='room_name',
            field=models.CharField(default='me', max_length=300),
        ),
    ]
