# Generated by Django 3.0.7 on 2020-06-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_lastmessage_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastmessage',
            name='room_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
