# Generated by Django 3.0.7 on 2020-06-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaInfoA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('bnName', models.TextField(blank=True, null=True)),
                ('cases', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoronaInfoC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('cases', models.TextField(blank=True, null=True)),
                ('todayCases', models.TextField(blank=True, default=0, null=True)),
                ('deaths', models.TextField(blank=True, null=True)),
                ('todayDeaths', models.TextField(blank=True, default=0, null=True)),
                ('recovered', models.TextField(blank=True, null=True)),
                ('todayRecovered', models.TextField(blank=True, default=0, null=True)),
                ('active', models.TextField(blank=True, null=True)),
                ('critical', models.TextField(blank=True, null=True)),
                ('casesPerOneMillion', models.TextField(blank=True, null=True)),
                ('deathsPerOneMillion', models.TextField(blank=True, null=True)),
                ('tests', models.TextField(blank=True, null=True)),
                ('testsPerOneMillion', models.TextField(blank=True, null=True)),
                ('population', models.TextField(blank=True, null=True)),
                ('continent', models.TextField(blank=True, null=True)),
                ('oneCasePerPeople', models.TextField(blank=True, null=True)),
                ('oneDeathPerPeople', models.TextField(blank=True, null=True)),
                ('oneTestPerPeople', models.TextField(blank=True, null=True)),
                ('activePerOneMillion', models.TextField(blank=True, null=True)),
                ('recoveredPerOneMillion', models.TextField(blank=True, null=True)),
                ('criticalPerOneMillion', models.TextField(blank=True, null=True)),
                ('flag', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='CoronaInfoD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('bnName', models.TextField(blank=True, null=True)),
                ('cases', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
