# Generated by Django 3.0.7 on 2020-06-26 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('last_submission', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('link', models.URLField()),
                ('solve', models.URLField()),
                ('text', models.TextField(blank=True, null=True)),
                ('tags', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('total_visit', models.TextField(blank=True, null=True)),
                ('creator', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('total_visit', models.TextField(blank=True, null=True)),
                ('creator', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('problems', models.ManyToManyField(blank=True, to='technique.Problems')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('total_visit', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(blank=True, to='technique.Keywords')),
                ('problems', models.ManyToManyField(blank=True, to='technique.Problems')),
                ('topic', models.ManyToManyField(blank=True, to='technique.Topic')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
