# Generated by Django 3.0.6 on 2020-05-30 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['topic_name'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_title', models.CharField(max_length=30)),
                ('tut_text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('topic_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Topics')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
