# Generated by Django 3.0.6 on 2020-06-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20200530_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
