# Generated by Django 3.0.6 on 2020-06-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_tutorial_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='beginner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
