# Generated by Django 3.0.6 on 2020-06-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_auto_20200607_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='hidden_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
