# Generated by Django 3.0.6 on 2020-06-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_auto_20200609_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestname',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
