# Generated by Django 3.0.6 on 2020-06-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_auto_20200609_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestname',
            options={'ordering': ['-end']},
        ),
        migrations.AddField(
            model_name='tutorial',
            name='question_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
