# Generated by Django 3.0.6 on 2020-06-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_auto_20200609_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='contest_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.ContestName'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='topic_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Topics'),
        ),
    ]
