# Generated by Django 3.0.8 on 2020-08-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0010_auto_20200812_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='title',
            new_name='tut_title',
        ),
    ]
