# Generated by Django 3.0.8 on 2020-08-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0012_auto_20200812_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='question_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
