# Generated by Django 3.0.7 on 2020-06-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200621_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announce',
            old_name='announcement_text',
            new_name='ann_text',
        ),
    ]
