# Generated by Django 3.0.7 on 2020-06-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200621_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, default=0, null=True)),
            ],
        ),
    ]
