# Generated by Django 3.0.8 on 2020-08-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_secretkeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='DData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'dData',
                'ordering': ['-added'],
            },
        ),
    ]
