# Generated by Django 3.0.8 on 2020-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddata',
            name='type',
            field=models.CharField(default='all', max_length=100),
        ),
    ]
