# Generated by Django 3.0.8 on 2020-07-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='handle',
            field=models.CharField(default='not_added', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profile',
            field=models.CharField(default='not_added', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='telegram_id',
            field=models.CharField(default='not_added', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_code',
            field=models.CharField(default='not_added', max_length=100),
        ),
    ]
