# Generated by Django 3.0.8 on 2020-07-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200731_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nick_name',
            field=models.CharField(default='not_added', max_length=100),
        ),
    ]
