# Generated by Django 3.0.8 on 2020-08-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinfo_nick_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['nick_name']},
        ),
    ]
