# Generated by Django 3.0.8 on 2020-08-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200803_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('NOT', 'NOT'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='NOT', max_length=5),
        ),
    ]
