# Generated by Django 3.0.8 on 2020-08-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
