# Generated by Django 3.0.8 on 2020-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200821_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
