# Generated by Django 3.0.8 on 2020-07-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uriinfo',
            options={'ordering': ['-solved']},
        ),
    ]
