# Generated by Django 3.0.8 on 2020-07-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_info', '0002_auto_20200715_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uriinfo',
            options={'ordering': ['-solves']},
        ),
        migrations.RemoveField(
            model_name='uriinfo',
            name='solved',
        ),
        migrations.AddField(
            model_name='uriinfo',
            name='solves',
            field=models.IntegerField(default=0),
        ),
    ]
